version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPASS}
      MYSQL_DATABASE: ${DBNAME}
    networks:
      - mynet
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysql", "-u$DBUSER",  "-p$DBPASS", "-e", "show databases;"]
      interval: 10s
  api:
    image: irvanhau/imgsimk
    depends_on:
      db:
        condition: service_healthy
        required: true
    environment:
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - DBHOST=db
      - DBPORT=${DBPORT}
      - DBNAME=${DBNAME}
      - SERVER=${SERVER}
    ports:
      - '8000:8000'
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
