// Code generated by mockery v2.35.2. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// MedicineCategoryHandlerInterface is an autogenerated mock type for the MedicineCategoryHandlerInterface type
type MedicineCategoryHandlerInterface struct {
	mock.Mock
}

// CreateMedicineCategory provides a mock function with given fields:
func (_m *MedicineCategoryHandlerInterface) CreateMedicineCategory() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// DeleteMedicineCategory provides a mock function with given fields:
func (_m *MedicineCategoryHandlerInterface) DeleteMedicineCategory() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// GetMedicineCategories provides a mock function with given fields:
func (_m *MedicineCategoryHandlerInterface) GetMedicineCategories() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// GetMedicineCategory provides a mock function with given fields:
func (_m *MedicineCategoryHandlerInterface) GetMedicineCategory() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// UpdateMedicineCategory provides a mock function with given fields:
func (_m *MedicineCategoryHandlerInterface) UpdateMedicineCategory() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// NewMedicineCategoryHandlerInterface creates a new instance of MedicineCategoryHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMedicineCategoryHandlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MedicineCategoryHandlerInterface {
	mock := &MedicineCategoryHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
