// Code generated by mockery v2.35.2. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// MedicalCheckupDetailHandlerInterface is an autogenerated mock type for the MedicalCheckupDetailHandlerInterface type
type MedicalCheckupDetailHandlerInterface struct {
	mock.Mock
}

// CreateMedicalCheckupDetail provides a mock function with given fields:
func (_m *MedicalCheckupDetailHandlerInterface) CreateMedicalCheckupDetail() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// DeleteMedicalCheckupDetail provides a mock function with given fields:
func (_m *MedicalCheckupDetailHandlerInterface) DeleteMedicalCheckupDetail() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// GetMedicalCheckupDetail provides a mock function with given fields:
func (_m *MedicalCheckupDetailHandlerInterface) GetMedicalCheckupDetail() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// GetMedicalCheckupDetails provides a mock function with given fields:
func (_m *MedicalCheckupDetailHandlerInterface) GetMedicalCheckupDetails() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// UpdateMedicalCheckupDetail provides a mock function with given fields:
func (_m *MedicalCheckupDetailHandlerInterface) UpdateMedicalCheckupDetail() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// NewMedicalCheckupDetailHandlerInterface creates a new instance of MedicalCheckupDetailHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMedicalCheckupDetailHandlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MedicalCheckupDetailHandlerInterface {
	mock := &MedicalCheckupDetailHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
